### PR TITLE
update turf modules & .001 meter tolerance to area check

### PR DESCRIPTION
**Pull request by morganherlocker**
- Fixes an [upstream nested dependency fail](https://github.com/bjornharrtell/javascript.util/issues/10) in jsts. The latest turf dependencies now shrinkwrap the failed lib inside jsts. 
- Slight behavior changes in jsts upstream also caused intersections at edges to be treated slightly differently. This led to near-zero area polygons slivers in the tile-cover tests. I added a small tolerance (0.001 meters) to this check.

cc @ingalls @karenzshea @yhahn @kelvinabrokwa

### CODE REVIEW

**Comment by morganherlocker** [comment]
travis builds are failing, but all tests pass when i run locally from a scratch-cloned repo. :/

**Comment by morganherlocker** [comment]
this failure happens on node 0.8.x and 0.10.x but not 0.12.x or io.js   O_o https://travis-ci.org/mapbox/tile-cover/jobs/55696154

**Comment by morganherlocker** [comment]
0.12 & io.js 1.6:



0.8 & 0.10:

**Comment by morganherlocker** [comment]
I found the discrepency buried deep in the callstack, inside tilebelt. There is [a call to Math.exp](https://github.com/mapbox/tilebelt/blob/master/index.js#L37), which returns ever so slightly different results in the latest version of V8. I believe that this is actually fixing a bug in previous versions, and the results now more closely match the intent of the code. 

```js
Math.exp(0.3650874275167828)

// node v0.10
// 1.4406399542173363
// node v0.12
// 1.440639954217336
```

This affected only one cover out of hundreds of tests and the results are still good (all geometries were still covered), so I feel good about overwriting this fixture to get tests to pass. 

@yhahn I am considering modifying the .travis.yml file to target node 0.12 only. What do you think? Should we have version specific assertions, or is that overkill?

**Comment by mourner** [comment]
@morganherlocker what did you decide here? Also discovered that failing test today... Maybe we could try making the math in tilebelt more reliable somehow.

**Comment by mourner** [comment]
Looks like we have a good fix (see https://github.com/mapbox/tilebelt/issues/22).

**Pull request merged**
