### PR TITLE
Much better polygon cover algorithm

### LINKED ISSUE #58: Scanline algorithm without intersections
It just suddenly occurred to me that there might be a way to get scanline polygon cover without ever calculating intersections at all (and thus not needing active edge table and similar techniques).

All we theoretically need is launching the line-cover algo, which is super-fast, but instead of saving tiles in a hash map, save them in a 2-dimensional array with each element corresponding to Y coord (so that `tiles[y]` is a list of tiles on the Y coord).  We would also need to track local minima/maxima as we go. 

What we essentially get is a list of all tile "intersections" per Y scanline, without ever needing to actually calculate an intersection. This could be potentially super-blazing-fast. What do you think?

### PR DESCRIPTION
**Pull request by mourner**
Makes polygon cover algorithm pretty much as fast and simple as it can get. Closes #58. 

- ~20-25% faster according to benchmarks (update: up to 3x faster)
- fixes cover bugs (see unnecessary tiles removed in the out files)
- much much simpler, tons of code removed

@morganherlocker @yhahn you'll like this!

### CODE REVIEW

**Comment by mourner** [comment]
41 additions and 681 deletions, isn't that just cool? My favourite type of PRs.

**Comment by yhahn** [comment]
@mourner awesome, RIP local min/max ascii art diagrams :joy:

**Comment by morganherlocker** [comment]
reviewing...

roadrunner

**Comment by mourner** [comment]
Pushed 2 more changes:

- faster merge algorithm that leads to ~20% faster polygon cover when it's merged
- fix multipoint not being merged

**Comment by mourner** [comment]
Pushed another perf improvement that leads to up to 3x gain in some polygon cases (where there are a lot of fills):

```bash
# before
scan russia polygon - z6 - z6 x 4,849 ops/sec ±2.24% (23 runs sampled)
scan russia polygon - z8 - z8 x 429 ops/sec ±3.56% (22 runs sampled)
scan russia polygon - z10 - z10 x 25.72 ops/sec ±1.72% (13 runs sampled)
scan russia polygon multizoom - z0 - z9 x 80.18 ops/sec ±2.82% (18 runs sampled)

# after
scan russia polygon - z6 - z6 x 6,493 ops/sec ±2.12% (23 runs sampled)
scan russia polygon - z8 - z8 x 1,001 ops/sec ±2.20% (23 runs sampled)
scan russia polygon - z10 - z10 x 81.71 ops/sec ±8.53% (18 runs sampled)
scan russia polygon multizoom - z0 - z9 x 113 ops/sec ±3.30% (19 runs sampled)
```

**Comment by morganherlocker** [comment]
:racehorse: published in v3.0.1!

**Comment by mourner** [comment]
Ha, you're a risky guy for publishing a patch version after half of the code rewritten from scratch :) Thanks Morgan!

**Comment by morganherlocker** [comment]
@mourner I thought about doing a major, but decided a patch made more sense. This did not change anything functionally (that we know of), other than bugs. If we find any functional - but valid - differences, we can roll this back and publish a major version bump. 

That's semver for you ¯\/(°_o)\/¯

**Pull request merged**
